// This file is auto-generated by ./bin/rails generate stimulus:manifest
// Run each time you add a new controller with `rails generate stimulus controllerName`

import { application } from "./application"

import PreviewController from "./preview_controller"
import TabsController from "./tabs_controller"
import RatingController from "./rating_controller"
application.register("preview", PreviewController)
application.register("tabs", TabsController)
application.register("rating", RatingController)
